# Generated by Django 5.1.6 on 2025-04-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='product_images/'),
        ),
    ]
