# Generated by Django 5.1.6 on 2025-03-11 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_comment_comment_message_comment_approach_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='approach',
            field=models.BooleanField(default=True),
        ),
    ]
