# Generated by Django 5.1.6 on 2025-03-11 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_comment_approach'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='profile_image',
            field=models.ImageField(default='profile_image_commenter/default.png', upload_to='profile_image_commenter/'),
        ),
    ]
