# Generated by Django 5.1.6 on 2025-03-12 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_comment_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='approach',
            field=models.BooleanField(default=False),
        ),
    ]
