# Generated by Django 5.1.6 on 2025-03-27 20:21

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_comment_approach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='published_date',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True),
        ),
    ]
